development:
  secret_key_base:          6a4000110d6fdf56065d53c77d541d022de7ecdf2119d68e6277b568388658541d2f86f781bdda25c139e1259fa50f9640b89a0e9b6e8b7eea6d28eb0d0884ec
  facebook_app:             596417443712848
  facebook_secret:          fb0ce0e4d05f14e06d8948f82f7aee6b
  facebook_scope:           "email"
  twitter_api_key:          437398970-bFoAl4kmVSjduJE3qScW5teN9xFL2PtB6UKmoZSi
  twitter_api_secret:       dBxtY2mtpt7S7rb2Hz8hNQBT5N6OE25EQNsu12FoaA
  twitter_consumer_key:     10aSikg1srWKJgnBfv6HmQ
  twitter_consumer_secret:  uC3id25gASzZqjo2VEcTV1RJejNH4SLCwHykB5w3TM

test:
  secret_key_base:          9bb862d9fefa32081ba5b198474a99505de9fc2b853e5af32b4e7fd306ceaf675419b1aea2196506df6676156eba894bc5204578b8cfd86309c068d85e816db0
  facebook_app:             596417443712848
  facebook_secret:          fb0ce0e4d05f14e06d8948f82f7aee6b
  facebook_scope:           "email"
  twitter_api_key:          437398970-bFoAl4kmVSjduJE3qScW5teN9xFL2PtB6UKmoZSi
  twitter_api_secret:       dBxtY2mtpt7S7rb2Hz8hNQBT5N6OE25EQNsu12FoaA
  twitter_consumer_key:     10aSikg1srWKJgnBfv6HmQ
  twitter_consumer_secret:  uC3id25gASzZqjo2VEcTV1RJejNH4SLCwHykB5w3TM

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
